# _config.yml
# This is the main configuration file for your Jekyll site
# It defines site-wide variables and settings that Jekyll uses to generate your static site
# Modify these settings to customize your portfolio website

# Site settings
title: Isamu Thung # Your name or the title of your portfolio
email: example@gmail.com # Your email address
description: >- # This means to ignore newlines until the next key
  A portfolio website showcasing my work, writings, and projects.
  Built with Jekyll and hosted on GitHub Pages.
baseurl: "/Isamu" # The subpath of your site, e.g. /blog
url: "https://firecracker280.github.io" # The base hostname & protocol for your site, e.g. http://example.com
twitter_username: yourusername # Your Twitter username
github_username: yourusername # Your GitHub username
linkedin_username: yourusername # Your LinkedIn username

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# Collections settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
  writings:
    output: true
    permalink: /writings/:path/

# Default front matter settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "writings"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache
  - gemfiles
  - README.md
