# Site settings
title: "Firecracker280 - Portfolio"
description: "Personal portfolio website showcasing projects, writings, and journal entries"
baseurl: "/Isamu"  # Subpath of your site (matches repo name)
url: "https://firecracker280.github.io"  # GitHub Pages domain
email: your-email@example.com
github_username: firecracker280
linkedin_username: yourusername
twitter_username: yourusername

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:collection/:title/
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'node_modules', 'vendor']

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/
  writings:
    output: true
    permalink: /writings/:title/
  journal:
    output: true
    permalink: /journal/:title/

# Defaults (Front Matter)
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: "writings"
    values:
      layout: "post"
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: "journal"
    values:
      layout: "journal"
      comments: false
      share: false
      related: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins (Only GitHub Pages Supported Plugins)
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Sass (CSS Preprocessing)
sass:
  sass_dir: _sass
  style: compressed

# SEO Settings
twitter:
  username: yourusername
  card: summary_large_image
logo: "/assets/images/logo.png"
social:
  name: "Firecracker280"
  links:
    - https://twitter.com/yourusername
    - https://www.linkedin.com/in/yourusername
    - https://github.com/firecracker280
